### ISSUE TITLE
Investigate and replace the document.click event logic

### ISSUE THREAD

**Issue by chrisaliotta** [quantalytix/react-dropdownbox#6]
@jennianelson When the component loses focus through a tab or other element focus event there is a routine that is run on our documentClick event. My concern is that if there are more than one dropdown boxes and a second one is selected that the first dropdown box will remain open based on the logic below.

```javascript
handleClick = (e) => {   
    // if there are multiple dropdowns rendered on a single page
    // will this logic create a problem?
    let found = e.path.find(el => el.className === "react-dropdown")
    if (!!!found) {
      this.closeDropdown();
      this.resetSelection();
    }
  }
```

I started hacking together a different process but I still think it might have the same problem (and at the moment this does not work):

```javascript
handleClick = (e) => {
    // we can use a forwardRef to potentially solve this...
    console.log(ReactDOM.findDOMNode(this.refs.dropdownbox)); // <div class="react-dropdown">...</div>
    console.log(document.activeElement); // <input class="input-box" placeholder="" ...>
    if (document.activeElement !== ReactDOM.findDOMNode(this.refs.dropdownbox)) {
      this.closeDropdown();
      this.resetSelection();
    }
}
```
Thoughts?

**Comment by jennianelson** [comment]
This was easy, and it worked: https://medium.com/@pitipatdop/little-neat-trick-to-capture-click-outside-react-component-5604830beb7f

One of the comments suggested exposing the child ref to the parent like this, but did not give any reason why one approach is preferred over another.

```
class Parent extends React.Component {
  constructor(props){
    super(props);
    this.childRef = React.createRef();
  }
  render() {
    <Child domRef={this.childRef} />
  }
}
class Child extends React.Component {
  render() {
    return <div ref={this.props.domRef}>Parent knows about me</div>
  }
}
```
